### PR TITLE
Highly available NAT Gateway example

### PR DESCRIPTION
**Pull request by Dnefedkin**
This example shows how to create a highly available NAT gateway in several zones of a GCP region. It can be used by GCE VMs with internal only IP addresses to access internet resources. Traffic is balanced between the NAT gateways using equal cost based routing with equal route priorities to the same instance tag.

### CODE REVIEW

**Comment by shuainie-google** [comment]
Hi @Dnefedkin, please refactor the pull request and move the sample under /deploymentmanager-examples/community folder. Thanks

**Comment by shuainie-google** [comment]
Hi @Dnefedkin, any update? Thanks

**Comment by likeulb** [comment]
Hi @Dnefedkin, please refactor the pull request and move the sample under /deploymentmanager-examples/community folder. Thanks

**Comment by Dnefedkin** [comment]
@likeulb , @shuainie-google -  I moved the sample to the community folder

**Pull request merged**
